class TokenType:
    def __init__(self):
        self.int_value = "intvalue"
        self.string_value = "stringvalue"
        self.real_value = "realvalue"
        self.anonymous = "anonymous"

        self.binary_operation = "binaryoperation"
        self.assignment_binary_operation = "assignmentbinaryoperation"
        self.assignment_operator = "assignmentoperator"

        self.equal = "equal"
        self.not_equal = "notequal"
        self.greater_than = "greaterthan"
        self.greater_than_equal = "greaterthanequal"
        self.less_than = "lessthan"
        self.less_than_equal = "lessthanequal"
        self._and = "and"
        self._or = "or"

        self.lineend = "lineend"
        self.eof = "eof"

        self.open_parenthesis = "openparenthesis"
        self.close_parenthesis = "closeparenthesis"
        self.open_brace = "openbrace"
        self.close_brace = "closebrace"
        self.open_bracket = "openbracket"
        self.close_bracket = "closebracket"
        self.colon = "colon"
        self.comma = "comma"
        self.period = "period"
        self.single_quote = "singlequote"
        self.double_quote = "doublequote"
        self._return = "return"

        self.identifier = "identifier"

        # keywords
        self._continue = "continue"
        self.unknown = "unknown"
        self._lambda = "lambda"
        self._import = "import"
        self.string = "string"
        self.export = "export"
        self._while = "while"
        self._break = "break"
        self.array = "array"
        self.obj = "object"
        self._else = "else"
        self.real = "real"
        self.bool = "bool"
        self.each = "each"
        self._try = "try"
        self._for = "for"
        self.int = "int"
        self._if = "if"
        self._in = "in"
        self._as = "as"
        self.fn = "fn"
        self.do = "do"
        self.catch = "catch"
        self.throw = "throw"
        self._case = "case"
        self._match = "match"
        self._del = "del"